apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nodejs-tinsuyqe
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/nodejs-tinsuyqe:644038a1b473cde5d1a48f44fcbea9f552fed476@sha256:5c75289a1381d62e48a7e69231ca0f1612a0318d10bc81b09e7803983d3d8f0d
          name: container-image
